"""Generate the zone and dock backgrounds as flat low-poly SVGs (Docs/ART_STYLE.md).

Flat colour bands, jagged torn-paper pines, layered fog that gets lighter with
distance, water with reflections and broken foam lines. Seeded, so the output
is stable; tweak the scene functions and rerun:

    python tools/make_backgrounds.py

Writes art/backgrounds/lake.svg, river.svg, dock.svg (1920×1080). The horizon
sits at 60 % height and the centre stays calm for the game's status text.
"""
import math
import os
import random

W, H = 1920, 1080
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "art", "backgrounds")

# Palette (ART_STYLE.md §2)
INK_SOFT, WOOD_DARK, WOOD = "#121413", "#241f1d", "#4c3932"
MAROON_DARK, MAROON, SLATE = "#3e211c", "#5c2427", "#273244"
UMBER, RUST, OCHRE_DARK, OCHRE, SAND = "#654831", "#7d5230", "#876446", "#a68554", "#b7a072"
PAPER_DARK, PAPER, PAPER_LIGHT = "#bfaf96", "#d5c8af", "#eee4cf"
NIGHT, DEEP_TEAL, STEEL, SEA, MIST, FOAM = "#0a1426", "#0f282e", "#344551", "#3f5e6a", "#62878f", "#a3bdbe"
LANTERN = "#f3d27a"


class Svg:
    def __init__(self):
        self.defs, self.parts = [], []

    def add(self, s):
        self.parts.append(s)

    def rect(self, x, y, w, h, fill, opacity=1.0):
        self.add(f'<rect x="{x:.0f}" y="{y:.0f}" width="{w:.0f}" height="{h:.0f}" fill="{fill}" opacity="{opacity}"/>')

    def poly(self, pts, fill, opacity=1.0, stroke=None, sw=0):
        p = " ".join(f"{x:.0f},{y:.0f}" for x, y in pts)
        s = f' stroke="{stroke}" stroke-width="{sw}" stroke-linejoin="round"' if stroke else ""
        self.add(f'<polygon points="{p}" fill="{fill}" opacity="{opacity}"{s}/>')

    def glow(self, cx, cy, r, color, opacity):
        gid = f"g{len(self.defs)}"
        self.defs.append(f'<radialGradient id="{gid}"><stop offset="0" stop-color="{color}" stop-opacity="{opacity}"/>'
                         f'<stop offset="1" stop-color="{color}" stop-opacity="0"/></radialGradient>')
        self.add(f'<circle cx="{cx:.0f}" cy="{cy:.0f}" r="{r:.0f}" fill="url(#{gid})"/>')

    def write(self, name):
        body = "\n  ".join(self.parts)
        defs = f"<defs>{''.join(self.defs)}</defs>\n  " if self.defs else ""
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}">\n'
               f"  <!-- Generated by tools/make_backgrounds.py; edit that, not this. -->\n  {defs}{body}\n</svg>\n")
        with open(os.path.join(OUT, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(svg)
        print(f"wrote art/backgrounds/{name} ({len(svg) // 1024} KB)")


# --- Building blocks -----------------------------------------------------------------

def sky(svg, bands, horizon):
    for i, (y, color) in enumerate(bands):
        y2 = bands[i + 1][0] if i + 1 < len(bands) else horizon
        svg.rect(0, y, W, y2 - y + 1, color)


def torn_cloud(svg, rng, cx, cy, w, h, color, opacity):
    pts = []
    n = 14
    for i in range(n):
        a = 2 * math.pi * i / n
        r = 1 + rng.uniform(-0.25, 0.25)
        y_scale = 0.6 if math.sin(a) > 0 else 1.0  # flatter underside
        pts.append((cx + math.cos(a) * w / 2 * r, cy + math.sin(a) * h / 2 * r * y_scale))
    svg.poly(pts, color, opacity)


def ridge(svg, rng, base, amp, step, color, bottom, opacity=1.0):
    pts = [(0, bottom)]
    x, y = 0, base - rng.uniform(0, amp)
    while x <= W + step:
        pts.append((x, y))
        x += rng.uniform(step * 0.6, step * 1.4)
        y = min(base, max(base - amp, y + rng.uniform(-amp / 2, amp / 2)))
    pts.append((W, bottom))
    svg.poly(pts, color, opacity)


def pine(svg, rng, x, base, height, color, opacity=1.0):
    """Stacked tiers with torn, jagged lower edges (art2.jpg pines)."""
    width = height * rng.uniform(0.42, 0.55)
    tiers = rng.randint(3, 4)
    svg.rect(x - width * 0.04, base - height * 0.2, width * 0.08, height * 0.2, color, opacity)
    # Solid core so the notches between tiers never show the sky through the tree.
    svg.poly([(x, base - height * 0.95), (x + width * 0.16, base - height * 0.12), (x - width * 0.16, base - height * 0.12)], color, opacity)
    for t in range(tiers):
        f = t / tiers
        bottom = base - height * (0.12 + 0.8 * f)
        top = bottom - height * 0.42
        half = width / 2 * (1 - f * 0.7)
        pts = [(x + rng.uniform(-3, 3), top), (x + half, bottom)]
        steps = 6
        for s in range(1, steps):
            px = x + half - 2 * half * s / steps
            pts.append((px, bottom - rng.uniform(0, height * 0.035) if s % 2 else bottom + rng.uniform(0, height * 0.045)))
        pts.append((x - half, bottom))
        svg.poly(pts, color, opacity)


def treeline(svg, rng, xs, base, h_min, h_max, color, opacity=1.0, ground=True):
    trees = []
    for x0, x1, spacing in xs:
        x = x0
        while x < x1:
            trees.append((x, rng.uniform(h_min, h_max)))
            x += rng.uniform(spacing * 0.6, spacing * 1.3)
    if ground:
        for x0, x1, _ in xs:
            svg.poly([(x0 - 40, base + 4), (x0, base - h_min * 0.18), (x1, base - h_min * 0.18), (x1 + 40, base + 4)], color, opacity)
    for x, h in sorted(trees, key=lambda t: t[1]):
        pine(svg, rng, x, base, h, color, opacity)
    return trees


def reflection(svg, rng, trees, horizon, color, opacity, squash=0.45):
    for x, h in trees:
        hh = h * squash
        w = hh * 0.5
        svg.poly([(x - w / 2, horizon + 2), (x + w / 2, horizon + 2), (x + rng.uniform(-4, 4), horizon + hh)], color, opacity)


def water(svg, bands, horizon):
    sky(svg, bands, H)


def foam(svg, rng, n, y0, y1, color, opacity):
    for _ in range(n):
        y = rng.uniform(y0, y1)
        x = rng.uniform(-50, W)
        length = rng.uniform(30, 160) * (0.5 + (y - y0) / (y1 - y0))
        x2 = x
        while x2 < x + length:
            seg = rng.uniform(10, 40)
            svg.add(f'<path d="M{x2:.0f} {y:.0f} L{x2 + seg:.0f} {y + rng.uniform(-1, 1):.0f}" '
                    f'stroke="{color}" stroke-width="{1.5 + (y - y0) / (y1 - y0) * 2.5:.1f}" stroke-linecap="round" opacity="{opacity}"/>')
            x2 += seg + rng.uniform(6, 20)


def reeds(svg, rng, x0, x1, base, h_min, h_max, color, head):
    for _ in range(int((x1 - x0) / 9)):
        x = rng.uniform(x0, x1)
        h = rng.uniform(h_min, h_max)
        lean = rng.uniform(-h * 0.15, h * 0.15)
        w = rng.uniform(4, 8)
        svg.poly([(x - w / 2, base), (x + w / 2, base), (x + lean, base - h)], color)
        if rng.random() < 0.3:
            svg.poly([(x + lean * 0.8 - 5, base - h * 0.8), (x + lean * 0.85 + 5, base - h * 0.8),
                      (x + lean * 0.95 + 5, base - h * 0.92), (x + lean * 0.9 - 5, base - h * 0.92)], head)


def dock(svg, rng, left, right, top, deck, side, post, plank_line):
    """Wooden jetty coming in from the left foreground."""
    y_far, y_near = top, top + 110
    svg.poly([(left, y_near + 40), (right, y_far), (right, y_far + 26), (left, y_near + 70)], side)
    for px in range(left + 40, right, 150):
        t = (px - left) / (right - left)
        y = y_near + 40 + (y_far - y_near - 40) * t
        svg.rect(px, y + 10, 22 - 8 * t, 180 - 60 * t, post)
    svg.poly([(left, y_near), (right, y_far - 40), (right, y_far), (left, y_near + 40)], deck)
    for i in range(1, 12):
        t = i / 12
        x = left + (right - left) * t
        y_top = y_near + (y_far - 40 - y_near) * t
        svg.add(f'<path d="M{x:.0f} {y_top:.0f} L{x:.0f} {y_top + 40:.0f}" stroke="{plank_line}" stroke-width="3"/>')
    svg.rect(right - 30, y_far - 110, 26, 90, post)


def lantern(svg, x, y, glow_r=110):
    svg.rect(x - 4, y, 8, 70, INK_SOFT)
    svg.glow(x, y - 14, glow_r, LANTERN, 0.55)
    svg.poly([(x - 12, y - 30), (x + 12, y - 30), (x + 10, y), (x - 10, y)], LANTERN, 1, INK_SOFT, 3)
    svg.poly([(x - 14, y - 30), (x + 14, y - 30), (x, y - 42)], INK_SOFT)


# --- Scenes --------------------------------------------------------------------------

def lake():
    """Still Lake: calm, golden hour, reeds (DESIGN.md §7)."""
    rng = random.Random(7)
    svg = Svg()
    hz = 648
    sky(svg, [(0, OCHRE_DARK), (170, OCHRE), (330, SAND), (470, PAPER), (580, PAPER_LIGHT)], hz)
    svg.glow(1320, 560, 460, LANTERN, 0.55)
    svg.add(f'<circle cx="1320" cy="560" r="62" fill="{PAPER_LIGHT}"/>')
    for cx, cy, w in [(300, 150, 420), (820, 90, 300), (1580, 200, 460), (1120, 300, 260), (560, 380, 340)]:
        torn_cloud(svg, rng, cx, cy, w, w * 0.22, PAPER if cy > 250 else SAND, 0.75)
    ridge(svg, rng, 612, 70, 90, SAND, hz + 2)
    svg.rect(0, 580, W, hz - 580, PAPER_LIGHT, 0.35)
    mid = treeline(svg, rng, [(-20, 700, 34), (1180, 1940, 34)], hz, 70, 150, OCHRE_DARK)
    treeline(svg, rng, [(700, 1180, 60)], hz, 30, 60, OCHRE_DARK)
    near = treeline(svg, rng, [(-60, 330, 70), (1640, 1980, 70)], hz + 14, 220, 380, UMBER)
    water(svg, [(hz, PAPER), (700, SAND), (790, OCHRE), (900, OCHRE_DARK)], hz)
    reflection(svg, rng, mid, hz, OCHRE_DARK, 0.35)
    reflection(svg, rng, near, hz + 14, UMBER, 0.4)
    for i in range(12):  # sun glitter
        y = hz + 14 + i * 22
        w = 160 - i * 10 + rng.uniform(-20, 20)
        svg.rect(1320 - w / 2 + rng.uniform(-20, 20), y, w, 5, PAPER_LIGHT, 0.7 - i * 0.04)
    foam(svg, rng, 38, hz + 20, H - 40, PAPER_LIGHT, 0.5)
    reeds(svg, rng, 1520, 1920, H, 120, 260, UMBER, RUST)
    reeds(svg, rng, 520, 760, H, 80, 170, UMBER, RUST)
    dock(svg, rng, -20, 560, 800, OCHRE_DARK, UMBER, WOOD_DARK, UMBER)
    svg.write("lake.svg")


def river():
    """Misty River: fog, lanterns, blue-grey (DESIGN.md §7)."""
    rng = random.Random(11)
    svg = Svg()
    hz = 648
    sky(svg, [(0, SLATE), (200, STEEL), (380, SEA), (520, MIST)], hz)
    svg.glow(960, 520, 700, FOAM, 0.35)
    for cx, cy, w in [(240, 130, 480), (1000, 70, 380), (1620, 180, 520), (640, 300, 400), (1400, 340, 360)]:
        torn_cloud(svg, rng, cx, cy, w, w * 0.2, SEA if cy < 200 else MIST, 0.7)
    ridge(svg, rng, 590, 90, 110, SEA, hz + 2)
    svg.rect(0, 520, W, hz - 520, FOAM, 0.35)
    far = treeline(svg, rng, [(-20, 1940, 40)], hz - 8, 60, 140, SEA)
    svg.rect(0, 560, W, hz - 560, FOAM, 0.4)
    near = treeline(svg, rng, [(-60, 420, 64), (1520, 1980, 64)], hz + 14, 240, 420, SLATE)
    water(svg, [(hz, MIST), (700, SEA), (800, STEEL), (920, SLATE)], hz)
    reflection(svg, rng, far, hz, SEA, 0.5)
    reflection(svg, rng, near, hz + 14, SLATE, 0.5)
    svg.rect(0, hz - 10, W, 60, FOAM, 0.35)  # low fog on the water
    for x in (560, 900, 1260):
        lantern(svg, x, hz - 58)
        for i in range(8):
            svg.rect(x - 14 + rng.uniform(-6, 6), hz + 10 + i * 24, 28 - i * 2, 5, LANTERN, 0.45 - i * 0.04)
    foam(svg, rng, 36, hz + 20, H - 40, FOAM, 0.45)
    reeds(svg, rng, 1560, 1920, H, 140, 280, SLATE, STEEL)
    dock(svg, rng, -20, 560, 800, WOOD, WOOD_DARK, INK_SOFT, WOOD_DARK)
    lantern(svg, 543, 622, 90)  # stands on the jetty's end post
    svg.write("river.svg")


def harbour():
    """Dock screen: dusk harbour with a jetty, crates and a lighthouse far off."""
    rng = random.Random(3)
    svg = Svg()
    hz = 560
    sky(svg, [(0, NIGHT), (220, SLATE), (400, STEEL), (500, SEA)], hz)
    for cx, cy, w in [(360, 120, 520), (1300, 90, 460), (900, 260, 380), (1700, 300, 420)]:
        torn_cloud(svg, rng, cx, cy, w, w * 0.2, STEEL if cy > 200 else SLATE, 0.8)
    ridge(svg, rng, 520, 60, 120, SLATE, hz + 2)
    # Lighthouse on the far point.
    lx, ly = 1640, hz
    svg.poly([(lx - 30, ly), (lx + 30, ly), (lx + 18, ly - 170), (lx - 18, ly - 170)], PAPER)
    for i in range(3):
        y0 = ly - 30 - i * 50
        svg.poly([(lx - 28 + i * 4, y0), (lx + 28 - i * 4, y0), (lx + 26 - i * 4, y0 - 22), (lx - 26 + i * 4, y0 - 22)], MAROON)
    svg.glow(lx, ly - 190, 160, LANTERN, 0.6)
    svg.rect(lx - 16, ly - 200, 32, 30, LANTERN)
    svg.poly([(lx - 24, ly - 200), (lx + 24, ly - 200), (lx, ly - 230)], MAROON_DARK)
    water(svg, [(hz, SEA), (640, STEEL), (760, SLATE), (900, DEEP_TEAL)], hz)
    for i in range(10):
        svg.rect(lx - 12 + rng.uniform(-8, 8), hz + 8 + i * 22, 24, 4, LANTERN, 0.5 - i * 0.04)
    foam(svg, rng, 30, hz + 20, H - 60, FOAM, 0.35)
    # Big jetty in the foreground, planks converging.
    svg.poly([(0, 760), (1920, 700), (1920, 1080), (0, 1080)], WOOD)
    svg.poly([(0, 760), (1920, 700), (1920, 730), (0, 792)], OCHRE_DARK)
    for i in range(1, 16):
        x = i * 128
        svg.add(f'<path d="M{x} {760 - 60 * x / W:.0f} L{x - 140} 1080" stroke="{WOOD_DARK}" stroke-width="5"/>')
    for x, y, s in [(160, 700, 110), (270, 720, 80), (1500, 640, 120), (1620, 660, 90)]:
        svg.poly([(x, y), (x + s, y), (x + s, y + s * 0.8), (x, y + s * 0.8)], UMBER, 1, WOOD_DARK, 4)
        svg.poly([(x, y), (x + s, y), (x + s * 0.8, y - s * 0.25), (x - s * 0.2, y - s * 0.25)], OCHRE_DARK, 1, WOOD_DARK, 4)
    svg.add(f'<circle cx="420" cy="860" r="44" fill="none" stroke="{SAND}" stroke-width="12"/>')
    svg.add(f'<circle cx="420" cy="860" r="22" fill="none" stroke="{OCHRE}" stroke-width="8"/>')
    lantern(svg, 1780, 600, 150)
    svg.write("harbour.svg")


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    lake()
    river()
    harbour()
